### ISSUE TITLE
It is showing follwing error when using with docx file

### ISSUE THREAD

**Issue by shivbabbar0001** [joeblurton/doccounter#3]
Warning: ZipArchive::close(): Invalid or uninitialized Zip object in /home2/correcta/public_html/filetotext2/class.doccounter.php on line 240

Although it is also showing ok word counts which i desire, but also showing above error.

**Comment by joeblurton** [comment]
Interestingly this very issue was my task for the day. I'll let you know how I get on. It only seems to happen in certain word docs.

**Comment by joeblurton** [comment]
Fixed.
